### ISSUE TITLE
회원 가입 및 로그인 기능 개발

### ISSUE THREAD

**Issue by Y00NSJ** [KubeLabX/BE#1]
## 📝 Issue Title
회원 가입 API 개발

---

## 📌 Summary
- 작업의 목표: user 테이블 스키마 작성, 테스트 코드 작성, 회원 가입 API 작성
- 관련 기능/페이지: `/signup` 페이지, `BE/user/` 디렉터리

---

## ✅ Tasks

- [ ] user 테이블 ERD 수정
- [x] API 명세서 작성
- [x] `user/models.py` 에 DB 모델 정의
- [x] `user/tests.py`에 테스트 코드 작성
- [x] `user/views.py`에 API 로직 작성
- [x] 회원 가입 및 로그인 기능 테스트

---

## 📂 References

---

## 💡 Additional Context

- 테스트 코드 보완 필요
