### ISSUE TITLE
[강사용] 수업 생성 기능 개발

### ISSUE THREAD

**Issue by Y00NSJ** [KubeLabX/BE#2]
## 📝 Issue Title

[강사용] 수업 생성 기능 API 개발

---

## 📌 Summary

- 작업의 목표: 수업 생성 기능 API 개발 및 테스트 코드 작성+수행
- 관련 기능/페이지: `/class/create`

---

## ✅ Tasks

- [x] API 명세서 작성
- [ ] classes ERD 작성
- [x] 테스트 코드 작성
- [x] 구현 로직 작성

---

## 📂 References

---

## 💡 Additional Context

- 수업 코드 생성 로직 구현 필요
- JWT 인증 로직 구현 여부 논의
