### ISSUE TITLE
수업 리스트업 기능 개발

### ISSUE THREAD

**Issue by Y00NSJ** [KubeLabX/BE#5]
## 📝 Issue Title

참여 중인 수업 리스트업 기능 API 개발   

---

## 📌 Summary

- 작업의 목표: 학생 view / 강사 view 분리해 리스트업 api 개발하기 
- 관련 기능/페이지: `/course/list`

---

## ✅ Tasks

- [ ] API 명세서 작성
- [ ] courses 테이블 ERD 작성
- [ ] 테스트 코드 작성
- [ ] 학생 view 케이스 처리 로직 개발
- [ ] 교사 view 케이스 처리 로직 개발 

---
