### ISSUE TITLE
[학생용] 수강 신청 기능 개발  

### ISSUE THREAD

**Issue by Y00NSJ** [KubeLabX/BE#6]
## 📝 Issue Title

[학생용] 수강 신청 기능 개발 

---

## 📌 Summary

- 작업의 목표: 학생이 수업 코드를 통해 수강 신청하는 로직을 개발
- 관련 기능/페이지: `/course/register`

---

## ✅ Tasks

- [ ] **Step 1:** API 문서 작성
- [ ] **Step 2:** 테스트 코드 작성 
- [ ] **Step 3:** 로직 구현

---

## 💡 Additional Context

- 필드 충족 여부를 프론트 단에서 검사 요망
