### ISSUE TITLE
강의 최초 입장 시 Pod 할당

### ISSUE THREAD

**Issue by Y00NSJ** [KubeLabX/BE#8]
## 📝 Issue Title

[학생] 강의 수강 신청 시 Pod 할당

---

## 📌 Summary

- 작업의 목표: 강의 코드 입력해 강의실 최초 입장 시 해당 학생 전용 Pod 생성 및 할당, 관련 정보 DB에 저장
- 관련 기능/페이지: `/course/register`

---

## ✅ Tasks

- [ ] **Step 1:** `practice` 디렉토리에 `StudentPod` 테이블 스키마 선언: **학생(FK), 강의(FK)**, Pod명, 생성일시
- [ ] **Step 2:** Pod의 manifest 파일 작성
- [ ] **Step 3:** practice/views.register_course()에 Pod 생성 및 DB 데이터 추가 로직 작성
- [ ] **Step 4:** 테스트 코드 작성 및 디버깅

---

## 📂 References

- 관련 이슈: #6 

---

## 💡 Additional Context

- Pod명 : `{course.name.lower()}-{request.user.id}`
  - 강의명 한글일 시 처리
